### PR TITLE
feat: add optional purge system

### PR DESCRIPTION
**Pull request by Dolu89**

### CODE REVIEW

**Comment by staab** [comment]
What's this for? Seems simpler to just restart the server every x seconds

**Comment by Dolu89** [comment]
Restarting the server will kill subs. Also, cloud providers like railway.app or other don't have option to restart the server every x seconds

**Comment by staab** [comment]
Gotcha. What about an eviction policy, where events older than x are removed? If you're concerned about subs being nuked it seems good to not delete very recent events either

**Comment by Dolu89** [comment]
I wanted to do this first, but old events can't be pushed (pushed and deleted directly on the next round). Maybe it's useless to push old events, but who knows.
It's 2 cool solutions

EDIT: Another solution is to attach the current date to every pushed event. But it requires some changes

**Pull request merged**
